version: '3'

services:
  pubsub-emulator:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --project=my-project --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  dataflow-emulator:
    image: apache/beam_python3.8_sdk:latest
    command: python my_dataflow_job.py
    volumes:
      - /dataflow/sources/my_dataflow_job.py:/usr/src/myapp
    working_dir: /usr/src/myapp
